library(Matrix)
library(Seurat)
library(tidyverse)
exp <- readRDS("GSE204683_count_matrix.RDS")
sparse_expr <- Matrix(as.matrix(exp), sparse = TRUE)
Zhu2023 <- CreateSeuratObject(counts = sparse_expr, project = "Zhu2023")
saveRDS(Zhu2023, file = "Zhu2023.rds")

meta <- read_csv("meta_rna.csv") %>% select(...1, donor_id, sex, development_stage) %>% rename(barcode=...1, donorid=donor_id, age=development_stage)
meta$age <- gsub("23rd week post-fertilization stage", "23pcw", meta$age)
meta$age <- gsub("th week post-fertilization stage", "pcw", meta$age)
meta$age <- gsub("infant stage", "0y", meta$age)
meta$age <- gsub("-year-old stage", "y", meta$age)
meta$sex <- gsub("female", "F", meta$sex)
meta$sex <- gsub("male", "M", meta$sex)
write.csv(meta, "meta_Zhu2023.csv")
